# Generated by Django 4.2.30 on 2026-05-25 21:24

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawingslog",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Drawings Amount (KES)",
            ),
        ),
        migrations.AlterField(
            model_name="drawingslog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="drawingslog",
            name="month",
            field=models.PositiveSmallIntegerField(verbose_name="Month (1–12)"),
        ),
        migrations.AlterField(
            model_name="drawingslog",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="Year"),
        ),
        migrations.AlterField(
            model_name="expenselog",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Amount (KES)",
            ),
        ),
        migrations.AlterField(
            model_name="expenselog",
            name="category",
            field=models.CharField(
                choices=[
                    ("transport", "Transport & Delivery"),
                    ("utilities", "Utilities (Power, Water, Internet)"),
                    ("rent", "Rent / Premises"),
                    ("wages", "Casual Wages / Labour"),
                    ("marketing", "Marketing & Advertising"),
                    ("maintenance", "Maintenance & Repairs"),
                    ("professional", "Professional Services (Accountant, Legal)"),
                    ("consumable", "Consumables / Office"),
                    ("fuel", "Fuel & Vehicle"),
                    ("bank", "Bank Charges & Mobile Money"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expenselog",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="expenselog",
            name="description",
            field=models.CharField(max_length=300, verbose_name="Expense Description"),
        ),
        migrations.AlterField(
            model_name="expenselog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="expenselog",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("mpesa", "M-Pesa"),
                    ("bank", "Bank Transfer"),
                    ("card", "Card"),
                    ("other", "Other"),
                ],
                default="mpesa",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expenselog",
            name="reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Reference / Receipt No."
            ),
        ),
        migrations.AlterField(
            model_name="materialuselog",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Date Used"
            ),
        ),
        migrations.AlterField(
            model_name="materialuselog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="materialuselog",
            name="job_reference",
            field=models.CharField(
                blank=True,
                help_text="e.g. JC-0042 or Production Batch #7",
                max_length=100,
                verbose_name="Job / Batch Reference",
            ),
        ),
        migrations.AlterField(
            model_name="materialuselog",
            name="line_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=14,
                verbose_name="Line Cost (KES)",
            ),
        ),
        migrations.AlterField(
            model_name="materialuselog",
            name="material_name",
            field=models.CharField(max_length=200, verbose_name="Material Name"),
        ),
        migrations.AlterField(
            model_name="materialuselog",
            name="quantity_used",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantity Used",
            ),
        ),
        migrations.AlterField(
            model_name="materialuselog",
            name="source_purchase",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usages",
                to="compliance.purchaselog",
                verbose_name="Source Purchase (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="materialuselog",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilograms (kg)"),
                    ("g", "Grams (g)"),
                    ("ltr", "Litres (ltr)"),
                    ("ml", "Millilitres (ml)"),
                    ("m", "Metres (m)"),
                    ("m2", "Square Metres (m²)"),
                    ("m3", "Cubic Metres (m³)"),
                    ("ft", "Feet (ft)"),
                    ("pcs", "Pieces (pcs)"),
                    ("sht", "Sheets"),
                    ("set", "Set"),
                    ("roll", "Roll"),
                    ("bag", "Bag"),
                    ("box", "Box"),
                    ("bale", "Bale"),
                    ("lot", "Lot"),
                    ("hr", "Hours (hr)"),
                    ("day", "Days"),
                ],
                default="pcs",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="materialuselog",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost per unit at the time of use — reference historical purchase price",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Unit Cost at Use (KES)",
            ),
        ),
        migrations.AlterField(
            model_name="purchaselog",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Purchase Date"
            ),
        ),
        migrations.AlterField(
            model_name="purchaselog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="purchaselog",
            name="item_name",
            field=models.CharField(max_length=200, verbose_name="Item / Supply Name"),
        ),
        migrations.AlterField(
            model_name="purchaselog",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="Quantity",
            ),
        ),
        migrations.AlterField(
            model_name="purchaselog",
            name="receipt_ref",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Receipt / LPO Reference"
            ),
        ),
        migrations.AlterField(
            model_name="purchaselog",
            name="supplier",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Supplier Name"
            ),
        ),
        migrations.AlterField(
            model_name="purchaselog",
            name="total_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=14,
                verbose_name="Total Cost (KES)",
            ),
        ),
        migrations.AlterField(
            model_name="purchaselog",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "Kilograms (kg)"),
                    ("g", "Grams (g)"),
                    ("ltr", "Litres (ltr)"),
                    ("ml", "Millilitres (ml)"),
                    ("m", "Metres (m)"),
                    ("m2", "Square Metres (m²)"),
                    ("m3", "Cubic Metres (m³)"),
                    ("ft", "Feet (ft)"),
                    ("pcs", "Pieces (pcs)"),
                    ("sht", "Sheets"),
                    ("set", "Set"),
                    ("roll", "Roll"),
                    ("bag", "Bag"),
                    ("box", "Box"),
                    ("bale", "Bale"),
                    ("lot", "Lot"),
                    ("hr", "Hours (hr)"),
                    ("day", "Days"),
                ],
                default="pcs",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="purchaselog",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Unit Cost (KES)",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Amount Paid (KES)",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="client_name",
            field=models.CharField(max_length=200, verbose_name="Client / Buyer Name"),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="client_phone",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Client Phone"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Invoice Date"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Summary of what was sold",
                verbose_name="Description of Goods / Services",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="etims_cu_invoice_no",
            field=models.CharField(
                blank=True,
                help_text="Control Unit invoice number from KRA eTIMS portal",
                max_length=100,
                verbose_name="eTIMS CU Invoice Number",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="etims_registered",
            field=models.BooleanField(
                default=False,
                help_text="Has this transaction been recorded in the KRA eTIMS system?",
                verbose_name="eTIMS Invoice Raised",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="gross_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total revenue collected before any deductions",
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Gross Sales Amount (KES)",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="invoice_number",
            field=models.CharField(
                help_text="e.g. INV-2025-001",
                max_length=50,
                unique=True,
                verbose_name="Invoice Number",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partial", "Partially Paid"),
                    ("paid", "Fully Paid"),
                    ("overdue", "Overdue"),
                    ("cancelled", "Cancelled / Reversed"),
                ],
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
