# Generated by Django 4.2.30 on 2026-05-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0002_alter_drawingslog_amount_alter_drawingslog_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesinvoice",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                help_text="Automatically generated (e.g., MN-05-26-2026-00001)",
                max_length=50,
                unique=True,
                verbose_name="Invoice Number",
            ),
        ),
    ]
