# Generated by Django 4.2.30 on 2026-05-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_price",
            field=models.BooleanField(
                default=False,
                help_text='Display the price on the public storefront. Leave unchecked for past commissions — "Enquire for pricing" will show instead.',
            ),
        ),
    ]
