# Generated by Django 4.2.30 on 2026-05-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_show_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="badge",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("new", "New"),
                    ("bestseller", "Best Seller"),
                    ("sale", "Sale"),
                    ("limited", "Limited"),
                    ("custom", "Custom"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
