# Generated by Django 4.2.30 on 2026-05-25 21:24

from django.db import migrations, models
import partners.models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="designsubmission",
            name="design_file_1",
            field=models.FileField(
                blank=True,
                help_text="PDF, DWG, JPG, PNG (max 20 MB)",
                null=True,
                upload_to=partners.models.design_upload_path,
                verbose_name="Design File 1",
            ),
        ),
        migrations.AlterField(
            model_name="partnerapplication",
            name="address_details",
            field=models.TextField(
                blank=True,
                help_text="Building name, road, landmarks etc.",
                verbose_name="Additional Address Details",
            ),
        ),
        migrations.AlterField(
            model_name="partnerapplication",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Special pricing discount awarded to this partner",
                verbose_name="Partner Discount (%)",
            ),
        ),
        migrations.AlterField(
            model_name="partnerapplication",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="What type of projects do you work on?",
                verbose_name="Tell us about your business",
            ),
        ),
        migrations.AlterField(
            model_name="partnerapplication",
            name="partner_code",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated when application is approved",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Partner Code",
            ),
        ),
    ]
